language: java

notifications:
  email: false

before_install:
  - chmod +x prepare-build.sh
  - ./prepare-build.sh

script:
  - mvn test
  - mvn checkstyle:check

after_success:
  - mvn cobertura:cobertura coveralls:report
